"""Remove columns

Revision ID: 5373c447ddf5
Revises: 8b697d3b26a1
Create Date: 2018-02-06 06:32:44.895108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5373c447ddf5'
down_revision = '8b697d3b26a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitch', 'upvotes')
    op.drop_column('pitch', 'downvotes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('downvotes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pitch', sa.Column('upvotes', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
