"""Add upvote and downvote columns

Revision ID: 8b697d3b26a1
Revises: aef69b157b65
Create Date: 2018-02-06 05:59:08.851987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b697d3b26a1'
down_revision = 'aef69b157b65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('downvotes', sa.Integer(), nullable=True))
    op.add_column('pitch', sa.Column('upvotes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitch', 'upvotes')
    op.drop_column('pitch', 'downvotes')
    # ### end Alembic commands ###
